# Generated by Django 4.1.10 on 2023-08-11 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("randNum", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RandNum",
        ),
    ]
